baseURL = "http://example.org/"
languageCode = "ko-kr"
defaultContentLanguage = "en-us"
title = "Oh Data Science"
paginate = "10"
theme = "mainroad"

[Author]

name = "Tai Hwan Oh"

[Params]
pager = true
toc = true
description = "오! 데이터 사이언스 블로그입니다."
copyright = "Tai Hwan Oh"
opengraph = true
authorbox = true
mathjax = true

[Params.sidebar]
home = "left"
list = "right"

widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
recend_num = 5
tags_counter = false

[Params.widgets.social]

github = "https://github.com/dhxoghks95"
