baseURL = "http://example.org/"
languageCode = "ko-kr"
defaultContentLanguage = "en-us"
title = "Oh Data Science"
paginate = "10"
theme = "mainroad"

[Author]

name = "Tai Hwan Oh"

[Params]
pager = true
toc = true
description = "오! 데이터 사이언스 블로그입니다."
copyright = "Tai Hwan Oh"
opengraph = true
authorbox = true
mathjax = true
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.sidebar]
home = "left"
list = "right"

widgets = ["recent", "categories", "taglist", "social"]

[Params.widgets]
recend_num = 5
tags_counter = false

[Params.widgets.social]

github = "dhxoghks95"
